### ISSUE TITLE
Assess IOSPE codebase for any more features to adapt

### ISSUE THREAD

**Issue by gabrielbodard** [EpiDoc/EFES#16]

**Comment by gabrielbodard** [comment]
Jamie: is everything under IOSPE mined and replicated to your satisfaction? If so, please close this ticket. If not, comment on what remains to be done, and assign to "1.0" or "Future" as appropriate!

**Comment by ajenhl** [comment]
Support for bibliographic concordances needs to be added. It's the first case of a file in content/ needing to be a particular name (by default; it can be changed in the sitemap) for it to work, sadly. Otherwise I believe it's all done. I hadn't realised the concordance was something backed by the EpiDoc guidelines.

**Comment by ajenhl** [comment]
The handling of the concordance requires coming up with a rendering of tei:bibl, tei:biblStruct, etc, which is a well-known nightmare because they can contain basically anything, and everyone wants their bibliographic entries to look in their particular precise style. I propose that EFES just provides a basic rendering based on the simplest possible markup (ie, tei:bibl, no children of tei:author and tei:editor, etc? Even that will require some sort of specification of the desired output.

**Comment by ajenhl** [comment]
I have committed the bibliographic concordance work, even without any good display of bibliographic items, simply because the actual functionality is present and it involves changes to a bunch of files. Polina is working on a wiki page documenting this feature.

**Comment by gabrielbodard** [comment]
This looks done to me. There is a bibliography WP for EFES 2.0, so any incomplete work there will be reopened next year. Closing.
