### ISSUE TITLE
Desideratum: add "facet" filers to indices

### ISSUE THREAD

**Issue by gabrielbodard** [EpiDoc/EFES#32]
A desideratum that came from one of our stakeholders, and we have started to discuss the practicability of, is the ability to filter the results in the main indices (names, words, abbreviations, symbols, etc.) by some of all of the values of the facets in the browse function. I.e. if we have an index of abbreviations, which lists all the instances of that abbreviation (even if there are multiple in a single inscription, on different line numbers), a user would want to be able to filter those results to only those on inscriptions from a certain date range, or a certain text type, or a combination of several facets.

**Comment by ajenhl** [comment]
I would like to learn a lot more about the use case here, because this sounds like something that should be done in the search interface rather than as an index. Perhaps because I can see the use of an index giving text parts and line numbers for non-digital purposes, or for an overview, but why not combine search with the index information (minus text part and line number) so that one can see which abbreviations exist in inscriptions mentioning a particular person and containing a search term?

**Comment by ajenhl** [comment]
Also, there's a wiki page for collecting requirements and constructing a specification for the indices at https://github.com/EpiDoc/EFES/wiki/Indices-spec

**Comment by gabrielbodard** [comment]
As discussed with Poli a couple weeks ago, this turns out to be too hard to do as an index, and listing abbreviations in the faceted browse interface doesn't seem useful, so I think we should redlight this desideratum for now. Closing ticket.
