### ISSUE TITLE
Desideratum: download index results as CSV or similar

### ISSUE THREAD

**Issue by gabrielbodard** [EpiDoc/EFES#33]
Another desideratum we received was the option to download the results of an index (filtered or otherwise) or search in a tabular data format, CSV/JSON or similar. So a user could download the search results with columns for search term, result/context, inscription id, internal reference, etc., and load into their own database or data analysis tool.

**Comment by gabrielbodard** [comment]
We should spec what we mean by this, and what the CSV/JSON should look like. Any thoughts?

**Comment by ajenhl** [comment]
I was looking into this yesterday, and I think it's hard to get nice CSV from both search results and indices, because a lot of things have multiple values. I created a simple XML output for search results that makes it simple and obvious to have multiple values, but I don't know if this is desirable?

For indices, a CSV format would have few columns, one of which just being a big list of all the index locations, which you'd want to have both a URI and a name for. This sort of data is not a good fit for CSV, but it would be easy to do nicely in XML.

**Comment by gabrielbodard** [comment]
Reassigning to EFES 2.0, since it is a more complex question than we could handle in 1.0. To be merged with geovisualization and RDF export.
