### ISSUE TITLE
Dating criteria

### ISSUE THREAD

**Issue by cmroueche** [EpiDoc/EFES#59]
It would be useful to have an a-list of dating criteria, which would ensure consistency: this could provide a valuable search facet.

**Comment by gabrielbodard** [comment]
Can we come up with a list of values to include as criteria? (Starting from those in the EpiDoc ODD, I suppose…)

**Comment by sdigiulio** [comment]
USEP has a relatively constrained list that we came up with and which might be useful; it’s accessible in [the list of USEP controlled values](https://github.com/Brown-University-Library/usep-data/blob/master/resources/include_taxonomies.xml) (starting around l. 422). The general principle we used, if I'm remembering correctly, was to provide as brief a list as possible that still represented (close to) the full range of criteria that applied to dating decisions for our corpus, including values for unknown dating. That said, I'm fairly certain that it aligns pretty closely with what is already in the EpiDoc ODD, in which case that might make for the better starting point?

**Comment by gabrielbodard** [comment]
The only wrinkle here is that the `@evidence` attribute on `<origDate>` is technically defined as `teidata.enumerated` (and not `teidata.pointer`), so we expect to find the values defined in the ODD/schema, not in an internal or external authority list to which we point via URIs.

But of course the advantage (as Im sure both @cmroueche and @sdigiulio agree) of an XML authority list is that you can better express relationships between terms in a hierarchical taxonomy, partial synonyms, broader/narrower terms, etc. in an XML authority list, than in the flat list in a schema, which would help to resolve the minor conflicts between the [values for `@evidence` in the EpiDoc ODD](https://sourceforge.net/p/epidoc/code/HEAD/tree/trunk/schema/tei-epidoc.xml#l540) and the [USEP controlled values(https://github.com/Brown-University-Library/usep-data/blob/master/resources/include_taxonomies.xml).

I guess the important question is: do you **need** an authority list in order to create a normalised index in EFES? It makes it a bit safer, that's for sure…

**Comment by ajenhl** [comment]
From the technical side, an authority list is not required to make an index, whether normalised or not. See for example the lemma index.
