### ISSUE TITLE
Simplify renaming of facets

### ISSUE THREAD

**Issue by IreneVagionakis** [EpiDoc/EFES#67]
Unless I missed something, currently in order to change the facets labels in the search page it is necessary to edit the facets name in several files (tei-to-solr.xml, schema.xml, config.xmap, facet_query.xml). Would it be possible to *just* change the labels of facets as they appear in the search page instead of having to edit all those files?

**Comment by ajenhl** [comment]
Modify solr/results-to-html.xsl, specifically the template matching on lst[@name='facet_fields']/lst/@name in the mode search-results. You can add specific renaming of facets.

Alternatively, since this is wrapped in i18n:text, you can create translations for them (key is the name of the facet prefixed with "facet-". If you're making any use of i18n in your site, this is the better option.
